# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for the main project
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    versioning-strategy: increase
      
  # Maintain dependencies for the typescript template
  - package-ecosystem: "npm"
    directory: "/templates/typescript" # Location of package manifests
    schedule:
      interval: "daily"
    versioning-strategy: increase

  # Maintain dependencies for the javascript template
  - package-ecosystem: "npm"
    directory: "/templates/javascript" # Location of package manifests
    schedule:
      interval: "daily"
    versioning-strategy: increase
      
  # Maintain dependencies for the python template
  - package-ecosystem: "pip"
    directory: "/templates/python" # Location of package manifests
    schedule:
      interval: "daily"

